### ISSUE TITLE
Villagers sometimes lie about their prices

### ISSUE THREAD

**Issue by Nataly171** [samolego/SimpleVillagers#10]
Before I get into it I'll mention I'm not sure if this is actually caused by this mod, but it seems to be the most likely culprit. I also have infinite trading installed so that might be causing it too. I figured I'd open an issue here and see if you could look into it to tell if it actually is this mod causing it.

I can't reliably reproduce it, but sometimes a villager's prices randomly revert without updating the display. I could be trading for Mending at one emerald, then suddenly it costs 16 emeralds but doesn't tell me, so I end up wasting emeralds. As far as I remember, this only happens when exiting and reentering the trading menu at least once. This issue is always temporarily solved by picking up the villager and putting it back down. I suspect it may have something to do with villagers changing their prices.

I don't know if it'll help, but here's my [latest.log](https://github.com/samolego/SimpleVillagers/files/9332419/latest.log), in which I did a bunch of trading and paused to grab the log immediately after it happened. Looking at the log, I don't see any trace of the glitch actually happening, but I'm not great at reading this stuff haha.

**Comment by samolego** [comment]
So villagerd that have been already traded with (those who don't have the reroll button) have different prices? I doubt it's caused by this mod, as it doesn't interfere with any of the trading mechanics ...
If you mean the reroll gui though, prices there could be different (if villager was zombified / punched), although they should become "real" upon clicking on them.

**Comment by Nataly171** [comment]
Yeah I did a bit more investigation and I'm pretty sure it actually is caused by infinite trading. Still pretty neat that infinite trading's bug can be worked around with this mod haha
