### ISSUE TITLE
Why did the update stop?

### ISSUE THREAD

**Issue by Dooepo** [samolego/SimpleVillagers#11]
I like this mod very much, this is a very promising mod on fabric, but after using it for two weeks, there are still many problems, but I can't wait for the author's update, why? Why didn't the author update it? why!

**Comment by samolego** [comment]
I'm just a volunteer, with limited amounts of time. I have many projects, but not the time nor motivation to update all of them, sorry.

**Comment by Dooepo** [comment]
Thank you for your reply, I wish you a happy every day.
