### ISSUE TITLE
No regular updates.

### ISSUE THREAD

**Issue by jiwachow** [samolego/SimpleVillagers#13]
Hey. Is this (wonderful) project abandoned? I can't see updates for new snapshots and versions.

**Comment by samolego** [comment]
I've started working on 1.19.3 port, but just port, no new features. Kinda lacking time&motivation 😑

**Comment by jiwachow** [comment]
It's great to hear it's not abandoned. It's been tough for a lot of people recently. Hope you find your way. I found that CoPilot and ChatGPT increase my motivation greatly just after script, chat or two:) We don't deserve this tech:D 

Good luck on updating, if you'd like we can do pair programming some day.
