### ISSUE TITLE
Not really an Issue but request: Possible config option to mute the sounds of the Iron Farm?

### ISSUE THREAD

**Issue by Adzeiros** [samolego/SimpleVillagers#16]
Curious if it's possible to add a config option to mute the sounds of the Iron Farm? Just find it SUPER annoying to hear 12+ Iron golems dying every 5 minutes for 12 seconds haha

**Comment by samolego** [comment]
You can turn down the blocks volume 😁

**Comment by Adzeiros** [comment]
> You can turn down the blocks volume 😁

Can I do this individual of other blocks in MC? I do not wish to mute any other block but this one.

**Comment by uselessSABOTAGE** [comment]
Ditto this.
