### ISSUE TITLE
Block Recipes Do Not Show in REI

### ISSUE THREAD

**Issue by uselessSABOTAGE** [samolego/SimpleVillagers#17]
Hello,

I would like to see block recipes in REI, I thought I used to be able to do this.  Also, I see there's a trader block, but I can't determine the recipe. Anyway you could post it somewhere? 

Thanks!

**Comment by uselessSABOTAGE** [comment]
Update: I found the trader block in REI on my server - but I couldn't obtain/craft it. So, I made a test world in creative mode, but it doesn't show up in creative menu, but I can obtain it via REI cheating. Guessing this still a "coming soon" feature as the indication for where you put the workstation block is labeled "ToDo".

**Comment by samolego** [comment]
Trading block is not available, as it has some issues with infinite trading atm.
I'm not doing anything special for the recipes, that might be on rei side.
