### ISSUE TITLE
config option

### ISSUE THREAD

**Issue by ZorkIsEmo** [samolego/SimpleVillagers#19]
a config option to turn off the extra blocks to basically just have the trade reroller, would be the only trade reroller thats only server side

**Comment by samolego** [comment]
The whole mod is server side, even with blocks 😉

**Comment by ZorkIsEmo** [comment]
Yes but i dont want my players access to the blocks or the picking up villagers because we want it as vanilla as possible, iv just been putting things in that help that still feel very vanilla for them

**Comment by samolego** [comment]
You can disable the pickup with permissions, and blocks with crafting datapack.

**Comment by ZorkIsEmo** [comment]
How would i go about disabling it using a datapack?

**Comment by samolego** [comment]
You just override the default recipe, you can find info on internet 😉
