### ISSUE TITLE
THANK YOU FOR THIS!!! (and request :D)

### ISSUE THREAD

**Issue by Panderine** [samolego/SimpleVillagers#2]
I've been waiting for this for fabric for several years! Thanks!!!. Do you think you could be able to implement the "block" features of the original mod?.

Thanks again for this!!!

**Comment by samolego** [comment]
Yeah, I might try doing the blocks as well, but I have to figure out how they work first 😅 . They may take much more time to implement, especially with the time I have availabke rn.

**Comment by samolego** [comment]
I've done 2 blocks in 1.1.0 release. I'll continue to work on others.

**Comment by Panderine** [comment]
cool, its seems to be for 1.18.2 I'm not there quite yet :D
