### ISSUE TITLE
unable to load

### ISSUE THREAD

**Issue by mining1221** [samolego/SimpleVillagers#29]
just unable to get the mod to load up the launcher gives me this error it might just be on my end but iv reinstalled it a couple times

![image_2024-03-07_173358923](https://github.com/samolego/SimpleVillagers/assets/111200669/b0159e5d-c528-4910-be60-39bacbd617b7)

**Comment by samolego** [comment]
Please provide the logs as well. Which mc do you have?

**Comment by mining1221** [comment]
its for mc 1.20.1

**Comment by mining1221** [comment]
This is the only thing created when trying to load up mc 
[2024-03-09-1.log](https://github.com/samolego/SimpleVillagers/files/14546552/2024-03-09-1.log)
and this is the crash log
[crash-2024-03-09_09.19.50-client.txt crash log.txt](https://github.com/samolego/SimpleVillagers/files/14546575/crash-2024-03-09_09.19.50-client.txt.crash.log.txt)

**Comment by samolego** [comment]
Please remove config file in "config" directory inside .minecraft

**Comment by mining1221** [comment]
That worked thank you i shouldve thought of that months ago sorry for the trouble

**Comment by samolego** [comment]
Np :)
