### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by AsheeWolf** [samolego/SimpleVillagers#3]
Will there be a version for Fabric 0.12.11?

**Comment by samolego** [comment]
You mean old loader? Why'd you need that? 🤔

**Comment by AsheeWolf** [comment]
There's a modpack that uses Fabric 0.12.11 that I would like to use the mod for.

**Comment by samolego** [comment]
Does the modpack *require* that version specifically? (Because that's not really common among mods)

Have you tried updating fabric and running the modpack with mod in newer version?

**Comment by AsheeWolf** [comment]
I have not, I'm afraid if I update the fabric there would be mods that would not work because they might be the older version. I tried with this version and it told me that it would not work with this version.

**Comment by samolego** [comment]
Fabric is just the loader, most mods use >= for depending. You can always reinstall older version.
