### ISSUE TITLE
[1.20.4] Server crashes when iron farm block generating iron

### ISSUE THREAD

**Issue by Supernich** [samolego/SimpleVillagers#30]
Crashes with error
`
java.lang.NoSuchMethodError: 'net.minecraft.class_47 net.minecraft.class_47$class_48.method_309(net.minecraft.class_2960)'
        at org.samo_lego.simplevillagers.block.entity.IronFarmBlockEntity.produceIron(IronFarmBlockEntity.java:83)
        at org.samo_lego.simplevillagers.block.entity.IronFarmBlockEntity.serverTick(IronFarmBlockEntity.java:63)
`

Server details:
`
Details:
        Minecraft Version: 1.20.4
        Minecraft Version ID: 1.20.4
        Operating System: Linux (amd64) version 5.15.0-58-generic
        Java Version: 17.0.5, Eclipse Adoptium
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
        Memory: 3661073920 bytes (3491 MiB) / 8657043456 bytes (8256 MiB) up to 12884901888 bytes (12288 MiB)
        CPUs: 4
        Processor Vendor: GenuineIntel
        Processor Name: QEMU Virtual CPU version 4.2.0
        Identifier: Intel64 Family 6 Model 58 Stepping 9
        Microarchitecture: Ivy Bridge (Client)
        Frequency (GHz): -0.00
        Number of physical packages: 4
        Number of physical CPUs: 4
        Number of logical CPUs: 4
        Graphics card #0 name: unknown
        Graphics card #0 vendor: unknown
        Graphics card #0 VRAM (MB): 0.00
        Graphics card #0 deviceId: unknown
        Graphics card #0 versionInfo: unknown
        Virtual memory max (MB): 8000.75
        Virtual memory used (MB): 9646.04
        Swap memory total (MB): 0.00
        Swap memory used (MB): 0.00
        JVM Flags: 2 total; -Xmx12G -Xms4G
        Fabric Mods:
                architectury: Architectury 11.1.17
                biomesoplenty: BiomesOPlenty 19.0.0.63
                        com_electronwill_night-config_core: core 3.6.7
                        com_electronwill_night-config_toml: toml 3.6.7
                        net_jodah_typetools: typetools 0.6.3
                bookshelf: Bookshelf 23.0.6
                cloth-config: Cloth Config v13 13.0.121
                        cloth-basic-math: cloth-basic-math 0.6.1
                darkutils: DarkUtilities 19.0.6
                fabric-api: Fabric API 0.96.11+1.20.4
                        fabric-api-base: Fabric API Base 0.4.36+78d798af4f
                        fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.49+82b1bb3e4f
                        fabric-biome-api-v1: Fabric Biome API (v1) 13.0.16+78d798af4f
                        fabric-block-api-v1: Fabric Block API (v1) 1.0.16+3e2216cb4f
                        fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.4+78d798af4f
                        fabric-command-api-v1: Fabric Command API (v1) 1.2.41+f71b366f4f
                        fabric-command-api-v2: Fabric Command API (v2) 2.2.20+78d798af4f
                        fabric-commands-v0: Fabric Commands (v0) 0.2.58+df3654b34f
                        fabric-containers-v0: Fabric Containers (v0) 0.1.86+df3654b34f
                        fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.15+78d798af4f
                        fabric-convention-tags-v1: Fabric Convention Tags 1.5.10+78d798af4f
                        fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.23+78d798af4f
                        fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.4+b90db5744f
                        fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.4+5c0133444f
                        fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.61+78d798af4f
                        fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.1+09fc25014f
                        fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.1+389931eb4f
                        fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.74+df3654b34f
                        fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.46+78d798af4f
                        fabric-item-api-v1: Fabric Item API (v1) 2.2.0+d6f2b0844f
                        fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.26+58f8c0124f
                        fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.0+a67ffb5d4f
                        fabric-loot-api-v2: Fabric Loot API (v2) 2.1.9+78d798af4f
                        fabric-message-api-v1: Fabric Message API (v1) 6.0.5+78d798af4f
                        fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.65+78d798af4f
                        fabric-networking-api-v1: Fabric Networking API (v1) 3.1.7+2e5ac5484f
                        fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.0.14+080016e44f
                        fabric-particles-v1: Fabric Particles (v1) 1.1.7+78d798af4f
                        fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.20+78d798af4f
                        fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.19+58f8c0124f
                        fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.42+73761d2e4f
                        fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.1+e761c6694f
                        fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.14+78d798af4f
                        fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.20+df798a894f
                        fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.55+78d798af4f
                        fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.11+eb30349a4f
                        fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.14+78d798af4f
                fabricloader: Fabric Loader 0.15.7
                        mixinextras: MixinExtras 0.3.5
                ferritecore: FerriteCore 6.0.3
                forgeconfigapiport: Forge Config API Port 20.4.3
                glitchcore: GlitchCore 1.0.0.59
                huskhomes: HuskHomes 4.6.1
                        adventure-platform-fabric: adventure-platform-fabric 5.11.0
                                net_kyori_adventure-api: adventure-api 4.15.0
                                net_kyori_adventure-key: adventure-key 4.15.0
                                net_kyori_adventure-platform-api: adventure-platform-api 4.3.2
                                net_kyori_adventure-text-logger-slf4j: adventure-text-logger-slf4j 4.15.0
                                net_kyori_adventure-text-minimessage: adventure-text-minimessage 4.15.0
                                net_kyori_adventure-text-serializer-ansi: adventure-text-serializer-ansi 4.15.0
                                net_kyori_adventure-text-serializer-gson: adventure-text-serializer-gson 4.15.0
                                net_kyori_adventure-text-serializer-json: adventure-text-serializer-json 4.15.0
                                net_kyori_adventure-text-serializer-plain: adventure-text-serializer-plain 4.15.0
                                net_kyori_ansi: ansi 1.0.3
                                net_kyori_examination-api: examination-api 1.3.0
                                net_kyori_examination-string: examination-string 1.3.0
                                net_kyori_option: option 1.0.0
                        com_h2database_h2: h2 2.2.220
                        com_mysql_mysql-connector-j: mysql-connector-j 8.3.0
                        fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
                        org_apache_commons_commons-pool2: commons-pool2 2.12.0
                        org_mariadb_jdbc_mariadb-java-client: mariadb-java-client 3.3.2
                        org_xerial_sqlite-jdbc: sqlite-jdbc 3.45.0.0
                        placeholder-api: Placeholder API 2.3.0+1.20.3
                        redis_clients_jedis: jedis 5.1.0
                java: OpenJDK 64-Bit Server VM 17
                lithium: Lithium 0.12.1
                minecraft: Minecraft 1.20.4
                openpartiesandclaims: Open Parties and Claims 0.20.4
                pfm: Paladin's Furniture 1.2.1
                pigpen: PigPen 17.0.3
                roughlyenoughitems: Roughly Enough Items 14.0.688
                        error_notifier: Error Notifier 1.0.9
                runelic: Runelic 21.0.3
                simplevillagers: Simple Villagers 1.4.6
                        config2brigadier: Config to Brigadier 1.2.5
                terrablender: TerraBlender 3.3.0.12
                universal-graves: Universal Graves 3.2.1+1.20.3
                        common-protection-api: Common Protection API 1.0.0
                        polymer-core: Polymer (Core) 0.7.5+1.20.4
                                polymer-networking: Polymer (Networking) 0.7.5+1.20.4
                                polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.7.5+1.20.4
                        polymer-resource-pack: Polymer (Resource Pack) 0.7.5+1.20.4
                        polymer-virtual-entity: Polymer (Virtual Entity) 0.7.5+1.20.4
                                polymer-common: Polymer (Common) 0.7.5+1.20.4
                                        packet_tweaker: Packet Tweaker 0.5.1+1.20.4
                        predicate-api: Predicate API 0.3.0+1.20.2
                        server_translations_api: Server Translations API 2.2.0+1.20.3-rc1
                        sgui: sgui 1.4.1+1.20.4
                xaerominimap: Xaero's Minimap 24.0.3
                xaeroworldmap: Xaero's World Map 1.38.1
        Server Running: true
        Player Count: 2 / 12; [class_3222['Chosee'/4, l='ServerLevel[world]', x=-595.67, y=95.17, z=1292.99], class_3222['Superni4'/43524, l='ServerLevel[world]', x=-494.76, y=94.00, z=1332.97]]
        Data Packs: vanilla, fabric, biomesoplenty (incompatible), bookshelf (incompatible), config2brigadier, darkutils (incompatible), fabric-convention-tags-v1, openpartiesandclaims (incompatible), pfm, runelic (incompatible), server_translations_api, simplevillagers, terrablender (incompatible), universal-graves, pfm-data-resources
        Enabled Feature Flags: minecraft:vanilla
        World Generation: Stable
        Is Modded: Definitely; Server brand changed to 'fabric'
        Type: Dedicated Server (map_server.txt)
`

Also is there any plan to update to latest minecraft version? When i tried to add this mod to minecraft client - it crashed and i removed it since it can work serverside only

**Comment by samolego** [comment]
You're lucky you got the mod to load 🙃. Didn't expect old version to even come that far in 1.20.4 😅.

Sadly I'm not planning to update this anytime soon, as I'm out of time for modding :/. If you know how to code, I'll gladly accept PR fix.
