### ISSUE TITLE
Converter Block and Villagers with trades

### ISSUE THREAD

**Issue by WillowMist** [samolego/SimpleVillagers#6]
The converter doesn't seem to be retaining any information on villagers that I put in.  Names and trades are reset when I retrieve the finished villager.

**Comment by samolego** [comment]
Oh, that's really bad. Thanks for reporting.

**Comment by WillowMist** [comment]
Not sure if it's related, but I also picked up a villager with a trade history, and when I put them down, I got a whole new villager (new name, no data).  I do not recall for sure if it was a More Villagers villager, or a Vanilla villager.  

(I feel like V in V for Vendetta introducing himself in a most verbose and voracious manner)

**Comment by samolego** [comment]
Could you post the mods you're using? This sounds as a conflict, as this has been tested numerous times (using only simplevillagers though).

**Comment by WillowMist** [comment]
The ones that affect Villagers are:

villagernames-1.18.2-4.0.3.jar
simplevillagers-1.2.0.jar
infinitevillagertrading-1.18.2-fabric0.47.10-1.1.jar

**Comment by WillowMist** [comment]
That last part did work before 1.2.0

**Comment by samolego** [comment]
What happens if you remove infinite trading?

**Comment by WillowMist** [comment]
Same.   I can give you the list of all the mods.

`Couplings-1.8.0+1.18.2.jar
Croptopia-1.18.2-FABRIC-1.8.3.jar
FallingTree-1.18.2-3.4.1.jar
Patchouli-1.18.2-67-FABRIC.jar
better-signs-and-frames-0.8.3.jar
cardinal-components-api-4.1.4.jar
carpet-extra-1.18.2-pre2-1.4.64.jar
chainsuspension-1.1.0.jar
chestrefill-1.0.0_fabric.jar
cloth-config-6.2.57-fabric.jar
copperhopper-0.0.5+1.18.1.jar
disguiselib-1.2.1-fabric.jar
expanded-weapon-enchanting-1.0.2.jar
fabric-carpet-1.18.2-1.4.66+v220228.jar
fabric-language-kotlin-1.7.2+kotlin.1.6.20.jar
fabric-tree-chopper-0.8.5.jar
fantasy-0.4.4+1.18.2.jar
feature_nbt_deadlock_be_gone_fabric-2.0.0+1.18.2-rc1.jar
ferritecore-4.2.0-fabric.jar
graves-2.0.0-rc.5+1.18.2.jar
grind-enchantments-1.4.0+1.17.1.jar
lazydfu-0.1.2.jar
ledger-1.2.4.jar
malilib-fabric-1.18.2-0.12.1.jar
modmenu-3.1.0.jar
morecmds-1.4.1.0+1.18.jar
morevillagers-FABRIC-1.18.2-3.2.0.jar
mostructures-1.4.1+1.18.2.jar
'phosphor-fabric-mc1.18.x-0.8.1 (1).jar'
phosphor-fabric-mc1.18.x-0.8.1.jar
placeholder-api-1.1.3+1.17.1.jar
player-pronouns-1.4.0+1.18.jar
polydex-0.1.2+1.18.2.jar
polymer-all-0.2.0-beta.37+1.18.2.jar
qsl-1.1.0-beta.6_qfapi-1.0.0-beta.10_fapi-0.51.1_mc-1.18.2.jar
repurposed_structures_fabric-4.0.2+1.18.2.jar
servercore-1.2.8-1.18.2.jar
simplequests-1.18-1.0.0-fabric.jar
simplevillagers-1.2.0.jar
styled-chat-1.2.3+1.18.jar
styledplayerlist-2.1.3+1.18.jar
villagernames-1.18.2-4.0.3.jar
watson-fabric-1.18.2-1.14.2.jar
`

**Comment by WillowMist** [comment]
Ok, think I've narrowed it down.  If I pick a villager up into one of my hotbar slots, it retains the NBT info.  If I pick them up and they go directly into my inventory, they get grabbed as Picked Villager, and they no longer have any saved info.

**Comment by samolego** [comment]
Huh, that's so strange, but thanks for narrowing it down. I might have some time tomorrow to test it.

**Comment by samolego** [comment]
I've managed to fix the pickup issue, however, the curing works normally for me :thinking: ...

**Comment by WillowMist** [comment]
It was probably the same issue.  I'd pick up a villager, lose the NFT, put them in the converter....
