### ISSUE TITLE
No recipe for trading block

### ISSUE THREAD

**Issue by ArneDeGeeter** [samolego/SimpleVillagers#9]
The trading block doesn't have a recipe yet, but it does work when given with command? Is there any reason why the recipe is disabled?

**Comment by samolego** [comment]
No, there's no reason for that. I thought it's enabled by default 😅

**Comment by Adzeiros** [comment]
What is the recipe for the trade block? Also, Roughly Enough Items doesn't show recipes for any

**Comment by samolego** [comment]
Oh, I remember now, there are still some bugs, therefore I left it out.
I'm not sure about the rei part though

**Comment by Adzeiros** [comment]
> Oh, I remember now, there are still some bugs, therefore I left it out. I'm not sure about the rei part though

Yea not sure, REI used to show some of the blocks but no recipes, now it doesn't show any of them. It's fine though I can look up the recipes on here.
